version: '3.8'
services:
    php:
        build: images/php

    nginx:
        build: images/nginx
        ports:
            - 80:80
        depends_on:
            - php

    cron:
        build: images/cron
        depends_on:
            - php
